export const keywords = [
  'Leben in Deutschland App',
  'Leben in Deutschland Test',
  'Leben in Deutschland Prüfung Vorbereitung',
  'Einbürgerungstest App',
  'Leben in Deutschland Fragen',
  'Einbürgerungstest 2025',
  'Deutschlandtest App',
  'LID Test Vorbereitung',
  'Leben in Deutschland Fragenkatalog',
  'LID Prüfungstraining',
  'Einbürgerung App',
  'Deutsch Staatsbürgerschaft Test',
  'Integrationskurs App',
  'Deutsche Geschichte Fragen',
  'Vorbereitung Einbürgerung',
  'Deutschtest für Zuwanderer',
  'B1 Prüfung Vorbereitung',
  '300 Fragen Leben in Deutschland',
  'LID Fragen Deutsch',
  'Leben in Deutschland Quiz',
  'German citizenship test app',
  'Germany naturalization test prep',
  'Life in Germany exam',
  'German immigration test',
  'Germany residency quiz',
  'Learn about Germany app',
  'German integration test',
  'Germany quiz app for newcomers',
  'Offline test preparation',
  'Practice mode',
  'Flashcards for exam',
  'Mock tests Germany',
  'Progress tracker',
  'Localized by Bundesland',
]
