name: Keep Supabase Active
on:
  schedule:
    - cron: '0 0 */3 * *' # Every 3 days at midnight
jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping endpoint
        run: curl -f https://leben.ibeanuhillary.com/api/keep-alive
